### ISSUE TITLE
Error adding plugin de.dustplanet.cordova.AndroidDarkModeSupport.

### ISSUE THREAD

**Issue by Mr-Zero88** [timbru31/cordova-plugin-android-dark-mode-support#33]
Hi i installed your plugin today and now my app ist crasching even after i uninstaled it.
it has the problem that is trys to load de.dustplanet.cordova.AndroidDarkModeSupport.

Stacktrace:
```
System.err: java.lang.ClassNotFoundException: de.dustplanet.cordova.AndroidDarkModeSupport
System.err:    at java.lang.Class.classForName(Native Method)
System.err:    at java.lang.Class.forName(Class.java:453)
System.err:    at java.lang.Class.forName(Class.java:378)
System.err:    at org.apache.cordova.PluginManager.instantiatePlugin(PluginManager.java:564)
System.err:    at org.apache.cordova.PluginManager.getPlugin(PluginManager.java:183)
System.err:    at org.apache.cordova.PluginManager.startupPlugins(PluginManager.java:108)
System.err:    at org.apache.cordova.PluginManager.init(PluginManager.java:96)
System.err:    at org.apache.cordova.CordovaWebViewImpl.init(CordovaWebViewImpl.java:119)
System.err:    at org.apache.cordova.CordovaActivity.init(CordovaActivity.java:152)
System.err:    at org.apache.cordova.CordovaActivity.loadUrl(CordovaActivity.java:227)
System.err:    at de.terraconnect.smarthome.MainActivity.onCreate(MainActivity.java:39)
System.err:    at android.app.Activity.performCreate(Activity.java:7327)
System.err:    at android.app.Activity.performCreate(Activity.java:7318)
System.err:    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
System.err:    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3094)
System.err:    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3257)
System.err:    at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
System.err:    at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
System.err:    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
System.err:    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1948)
System.err:    at android.os.Handler.dispatchMessage(Handler.java:106)
System.err:    at android.os.Looper.loop(Looper.java:214)
System.err:    at android.app.ActivityThread.main(ActivityThread.java:7050)
System.err:    at java.lang.reflect.Method.invoke(Native Method)
System.err:    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
System.err:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
System.err: Caused by: java.lang.ClassNotFoundException: Didn't find class "de.dustplanet.cordova.AndroidDarkModeSupport" on path: DexPathList[[zip file "/data/app/de.terraconnect.smarthome-dUL3NQv8pLh0Bq2aJlXJUw==/base.apk"],nativeLibraryDirectories=[/data/app/de.terraconnect.smarthome-dUL3NQv8pLh0Bq2aJlXJUw==/lib/arm64, /system/lib64, /system/vendor/lib64]]
System.err:    at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
System.err:    at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
System.err:    at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
System.err:    ... 26 more
System.out: Error adding plugin de.dustplanet.cordova.AndroidDarkModeSupport.
AndroidRuntime: Shutting down VM
```

**Comment by timbru31** [comment]
Have you read the information in regards to the installation?
https://github.com/timbru31/cordova-plugin-android-dark-mode-support#prerequisiteswarnings

**Comment by timbru31** [comment]
Closing due to lack of feedback. If the issue persists, please create a new one.
